apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-client-qa
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp/payments-client
    targetRevision: HEAD
    path: .helm
    helm:
      values: | 
        image: 
          repository: image-registry.openshift-image-registry.svc:5000/payments-qa/payments-client
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: payments-qa
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m